### ISSUE TITLE
Future of dioxus charts

### ISSUE THREAD

**Issue by alexanderjophus** [hiltonm/dioxus-charts#3]
Hey, is it possible to update to either dioxus 0.4.0, or possibly donate the project to [dioxus-community](https://github.com/dioxus-community)?

I have forked and upgraded to 0.4.0 (was just a simple version bump). Would love to get it merged upstream. (Going to make a PR with that change now)

**Comment by hiltonm** [comment]
Sure, I would be happy to donate it to dioxus-community if there is interest on it. Are you involved in that project or just suggesting that I should approach them about it?

**Comment by alexanderjophus** [comment]
I was chatting to @marc2332 about it. Marc and a couple others maintain it. It's completely up to you, I'm starting a project which uses this and may ask for a few more features (I will be happy to create tickets/PRs for them).

**Comment by marc2332** [comment]
I am happy to accept dioxus-charts into the community org, you can join @hiltonm too if you want! The org is just a place to simplify the development of libraries of the community, So if you are no longer interested in developing it, or for any other reason you just can't maintain it, others can still contribute to it and release new versions 😄 It also serves as a "splotlight" for others to discover the projects and even contribute! 😄

**Comment by hiltonm** [comment]
Hey @alexanderjophus, glad to hear it. I hope it is useful for you!

@marc2332, yeah, I'm very busy with another project right now, so I won't be able to pull new code or release new versions quickly, let alone add new features, which should be annoying for Alex or anyone else that wants improvements. Let's do it then, do I need to add a link to your fork in the README to let people know that the project has moved, or you guys want it another way? I would also need to add a new user as an owner on crates.io first, right? What's the crates.io username?

Thank you very much for your interest in the project, both of you! :heart:

**Comment by marc2332** [comment]
> Hey @alexanderjophus, glad to hear it. I hope it is useful for you!
> 
> @marc2332, yeah, I'm very busy with another project right now, so I won't be able to pull new code or release new versions quickly, let alone add new features, which should be annoying for Alex or anyone else that wants improvements. Let's do it then, do I need to add a link to your fork in the README to let people know that the project has moved, or you guys want it another way? I would also need to add a new user as an owner on crates.io first, right? What's the crates.io username?
> 
> Thank you very much for your interest in the project, both of you! ❤️

heyy! Let's try transfering the repo from GitHub from your user to the [org](https://github.com/dioxus-community) if that's okay to you 😄 Maybe try adding me as maintainer to this repo so I can move it myself, otherwise I can add you to the org so you have permissions :p I am https://crates.io/users/marc2332 in crates.io :D

**Comment by hiltonm** [comment]
I sent the invites to you. Please, tell me if you need help with anything else! :ok_hand:

**Comment by alexanderjophus** [comment]
Thank you both! This crate is amazing btw.

**Comment by marc2332** [comment]
> I sent the invites to you. Please, tell me if you need help with anything else! 👌

Seems like I don't have enough permissions in this repo to move it, you can make me admin, or if you prefer (it's ok! 😄 ) I can invite you to the org so you can do it yourself :v: 😄

**Comment by hiltonm** [comment]
Yeah sorry, I didn't find how to change roles, it seems like its a Teams thing only and I would need an Organization for it first. I can see the button to make the transfer though! Please, add me to the org then so I can transfer it and you can remove me afterwards, no worries. :wink:

**Comment by hiltonm** [comment]
Also, of course I would be happy to be in the org and possibly help with this crate unless I have to participate in meetings, votings, etc. I can't commit to that right now.

**Comment by marc2332** [comment]
> Also, of course I would be happy to be in the org and possibly help with this crate unless I have to participate in meetings, votings, etc. I can't commit to that right now.

Just invited you 😄 Don't worry about meetings, votings, etc, we don't have that 😄 We talk async via [Discord](https://discord.com/channels/899851952891002890/1155572382157783141) or GitHub

**Comment by hiltonm** [comment]
The transfer is done! After checking out this new tree I noticed that the demos were missing their input.css :disappointed: I didn't see they were being blocked by the gitignore, so I fixed that and other clippy things. Just a quick release checklist in case you need that:

* run `cargo make dev` as a final check which should format, clippy and build the lib, you don't need to use those but it is a good way to remember all the commands :smile: 
* enter the examples folder and run `cargo make web` and `cargo make desktop`
* add any changes to CHANGELOG.md on its Unreleased section and commit that
* run `cargo release patch` to simulate and show the changes that will be made
* run `cargo release patch --execute` which will make some automated changes for versions, commit, tag and publish the crate

In case you never used cargo-release, it does take a long time to finish publishing. You may think it stopped working but just leave it alone and it will finish eventually.

I was going to write this on the wiki but I don't think it is supposed to be used for this kind of thing, right? Anyway, please tell me if there is anything wrong. :wink:

**Comment by marc2332** [comment]
omgg I forgot to answer you! Thanks for the tips!

Thank you!

**Comment by hiltonm** [comment]
No worries! :smile: By the way, I think we can close this issue now. Thanks for adopting the project, and thanks to Alex for suggesting it and putting us in touch, cheers!
